spring.application.name=notification
server.port=8081


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=juanbobadilla0104@gmail.com
spring.mail.password=wwit ooeo smwh licq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


twilio.account-sid=AC473579f0e2ae1b6fd0ec09b6a9109782
twilio.auth-token=8639490f80a3e63837ab3550d5c65528
twilio.phone-number=(952) 209-0582

