spring.application.name=notification
server.port=8081


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=TU_CORREO
spring.mail.password=TU_CONTRASENA
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


twilio.account-sid=ID_DE_TU_CUENTA_TWILIO
twilio.auth-token=TOKEN_DE_TWILIO
twilio.phone-number=+19522090582
